apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  type: NodePort
#  type: LoadBalancer
  sessionAffinity: None
  ports:
  - nodePort: 30705
    targetPort: 8000
    port: 8000
    protocol: TCP
  selector:
    app: currency-exchange


