apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consul
  name: consul
spec:
  template:
    metadata:
      labels:
        io.kompose.service: consul
    spec:
      containers:
      - args:
        - agent
        - -dev
        - -client
        - 0.0.0.0
        image: consul
        name: consul
        ports:
        - containerPort: 8301
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 8600
          protocol: UDP
      hostname: consul
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul

