apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: consul
  name: consul
spec:
  type: NodePort
  ports:
  - name: "8301"
    port: 8301
    targetPort: 8301
  - name: "8400"
    port: 8400
    targetPort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
    nodePort: 30500
  - name: "8600"
    port: 8600
    protocol: UDP
    targetPort: 8600
  selector:
    io.kompose.service: consul
