apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consul-server-2
  name: consul-server-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: consul-server-2
    spec:
      containers:
      - args:
        - agent
        - -server
        - -retry-join
        - consul-server-bootstrap
        - -client
        - 0.0.0.0
        image: consul:latest
        name: consul-server-2
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: consul-server-2
